# Lambda
version: '3'
services:
  lambda:
    image: lambci/lambda:nodejs12.x
    container_name: lambda
    # ホスト側は任意のディレクトリ
    volumes:
      - .:/var/task
    # 任意のパスワード
    environment:
      AWS_ACCESS_KEY_ID: <Set Your Access Key ID>
      AWS_SECRET_ACCESS_KEY: <Set Your Secret Access Key>
      AWS_REGION: <Set Your AWS Region>
    command:
      - index.handler 
      - '{"runtime": "nodejs12.x"}'

