# Lambda
version: '3'
services:
  lambda:
    image: lambci/lambda:nodejs12.x
    container_name: lambda
    # ホスト側は任意のディレクトリ
    volumes:
      - .:/var/task
    # 任意のパスワード
    environment:
      AWS_ACCESS_KEY_ID    : ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION           : ${AWS_REGION}
    command:
      - index.handler 
      - '{"runtime": "nodejs12.x"}'

